"""Changed column name

Revision ID: 763d53f9267f
Revises: 236ed811cd03
Create Date: 2024-03-01 23:11:27.387463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763d53f9267f'
down_revision: Union[str, None] = '236ed811cd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_book_user', 'reviews', ['book_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_book_user', 'reviews', type_='unique')
    # ### end Alembic commands ###
